# Generated by Django 5.0.4 on 2024-04-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('tin', models.CharField(max_length=12)),
                ('status', models.CharField(default='Не в работе', max_length=50)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_connector.user')),
            ],
        ),
    ]
